import { describe, it, expect } from 'vitest'
import { exportCss, exportCssReducedMotion } from './export'
import type { AnimationDocument } from '@/types'

const doc: AnimationDocument = {
  id: 'doc-1',
  name: 'Fade In',
  duration: 500,
  layers: [
    {
      id: 'layer-1',
      name: 'Box',
      visible: true,
      element: { tag: 'div', initialCss: '' },
      tracks: [
        {
          id: 'track-1',
          property: 'opacity',
          keyframes: [
            { id: 'kf-1', time: 0, value: '0', easing: 'ease-out' },
            { id: 'kf-2', time: 500, value: '1', easing: 'ease-out' },
          ],
        },
      ],
    },
  ],
}

describe('exportCss', () => {
  it('includes generator comment', () => {
    expect(exportCss(doc)).toContain('Generated by Keyforge')
  })

  it('includes animation name in comment', () => {
    expect(exportCss(doc)).toContain('Fade In')
  })

  it('strips --play-state var from exported CSS', () => {
    expect(exportCss(doc)).not.toContain('--play-state')
  })

  it('contains valid @keyframes block', () => {
    expect(exportCss(doc)).toContain('@keyframes')
  })
})

describe('exportCssReducedMotion', () => {
  const rmDoc: AnimationDocument = {
    id: 'doc-rm',
    name: 'Slide',
    duration: 800,
    layers: [
      {
        id: 'L1',
        name: 'Box',
        visible: true,
        element: { tag: 'div', initialCss: '' },
        tracks: [
          {
            id: 'T1',
            property: 'transform',
            keyframes: [
              { id: 'K1', time: 0, value: 'translateY(40px)', easing: 'ease-out' },
              { id: 'K2', time: 800, value: 'translateY(0px)', easing: 'linear' },
            ],
          },
        ],
      },
    ],
  }

  it('gates full-motion CSS behind no-preference', () => {
    const out = exportCssReducedMotion(rmDoc)
    expect(out).toContain('@media (prefers-reduced-motion: no-preference)')
    expect(out).toContain('translateY(40px)')
  })

  it('provides an opacity-only reduced fallback at half duration', () => {
    const out = exportCssReducedMotion(rmDoc)
    expect(out).toContain('@media (prefers-reduced-motion: reduce)')
    expect(out).toContain('kf-L1-reduced')
    expect(out).toContain('animation: kf-L1-reduced 400ms ease-out both;')
    // reduced variant must not contain movement
    const reduceBlock = out.split('(prefers-reduced-motion: reduce)')[1]
    expect(reduceBlock).not.toContain('translateY')
  })

  it('default exportCss output is unchanged (no media gates)', () => {
    const out = exportCss(rmDoc)
    expect(out).not.toContain('prefers-reduced-motion')
  })
})
