import { describe, it, expect } from 'vitest'
import { exportCss } from './export'
import type { AnimationDocument } from '@/types'

const doc: AnimationDocument = {
  id: 'doc-1',
  name: 'Fade In',
  duration: 500,
  layers: [
    {
      id: 'layer-1',
      name: 'Box',
      element: { tag: 'div', initialCss: '' },
      tracks: [
        {
          id: 'track-1',
          property: 'opacity',
          keyframes: [
            { id: 'kf-1', time: 0, value: '0', easing: 'ease-out' },
            { id: 'kf-2', time: 500, value: '1', easing: 'ease-out' },
          ],
        },
      ],
    },
  ],
}

describe('exportCss', () => {
  it('includes generator comment', () => {
    expect(exportCss(doc)).toContain('Generated by Keyforge')
  })

  it('includes animation name in comment', () => {
    expect(exportCss(doc)).toContain('Fade In')
  })

  it('strips --play-state var from exported CSS', () => {
    expect(exportCss(doc)).not.toContain('--play-state')
  })

  it('contains valid @keyframes block', () => {
    expect(exportCss(doc)).toContain('@keyframes')
  })
})
