import type { AnimationDocument } from '@/types'

/**
 * Export clean CSS — finite iteration shorthand, no preview-only properties.
 */
export function exportCss(doc: AnimationDocument): string {
  const css = doc.layers
    .map((layer) => {
      const animName = `kf-${layer.id}`

      const times = [
        ...new Set(layer.tracks.flatMap((t) => t.keyframes.map((k) => k.time))),
      ].sort((a, b) => a - b)

      if (times.length === 0) return ''

      const keyframeBlock = times
        .map((time) => {
          const pct = ((time / doc.duration) * 100).toFixed(2)
          const props = layer.tracks
            .map((track) => {
              const kf = [...track.keyframes].reverse().find((k) => k.time <= time)
              if (!kf) return ''
              return `${track.property}:${kf.value};`
            })
            .filter(Boolean)
            .join(' ')
          return `  ${pct}% { ${props} }`
        })
        .join('\n')

      return [
        `@keyframes ${animName} {`,
        keyframeBlock,
        `}`,
        `[data-layer-id="${layer.id}"] {`,
        `  animation: ${animName} ${doc.duration}ms linear both;`,
        `}`,
      ].join('\n')
    })
    .join('\n\n')

  return `/* Generated by Keyforge — ${doc.name} */\n\n${css}`
}
