import type { AnimationDocument, Layer } from '@/types'
import { buildSplitKeyframeBlocks } from './keyframes'

/**
 * Export production-ready CSS — finite animation, no preview-only properties.
 *
 * One @keyframes rule PER TRACK (always-split), matching preview generation:
 * a shared rule would inject false "hold" stops into sibling tracks at
 * foreign keyframe times (#51), and duplicate transform-TYPE tracks are
 * merged into a single composed transform channel by the block builder, so
 * same-property animations can never silently override each other
 * ("last one wins") in exported CSS.
 */
export function exportCss(doc: AnimationDocument): string {
  const css = doc.layers
    .map((layer) => {
      const animName = `kf-${layer.id}`
      return layerBlock(layer, doc.duration, animName)
    })
    .filter(Boolean)
    .join('\n\n')

  return `/* Generated by Keyforge — ${doc.name} */\n\n${css}`
}

function layerBlock(
  layer: Layer,
  duration: AnimationDocument['duration'],
  animName: string,
): string {
  const { times, blocks } = buildSplitKeyframeBlocks(layer, duration, animName)
  if (times.length === 0 || blocks.length === 0) return ''

  const names = blocks.map((b) => b.name).join(', ')
  return [
    ...blocks.map((b) => b.css),
    `[data-layer-id="${layer.id}"] {`,
    `  animation-name: ${names};`,
    `  animation-duration: ${duration}ms;`,
    `  animation-timing-function: linear;`,
    `  animation-fill-mode: both;`,
    `}`,
  ].join('\n')
}

/**
 * Reduced-motion-safe variant. Full-motion CSS is gated behind
 * (prefers-reduced-motion: no-preference); a calm fallback (opacity-only,
 * half duration) ships inside (prefers-reduced-motion: reduce) so content
 * still transitions meaningfully without vestibular risk.
 *
 * WCAG 2.2.2 / 2.3.3 friendly; recommended pattern per web.dev.
 */
export function exportCssReducedMotion(doc: AnimationDocument): string {
  const fullLayers: string[] = []
  const reducedLayers: string[] = []

  for (const layer of doc.layers as Layer[]) {
    const animName = `kf-${layer.id}`
    const full = layerBlock(layer, doc.duration, animName)
    if (!full) continue

    fullLayers.push(full)

    // Reduced variant: fade only, half duration, no transforms.
    const halfMs = Math.max(200, Math.round(doc.duration / 2))
    reducedLayers.push(
      [
        `@keyframes ${animName}-reduced {`,
        `  from { opacity: 0.25; }`,
        `  to { opacity: 1; }`,
        `}`,
        `[data-layer-id="${layer.id}"] {`,
        `  animation: ${animName}-reduced ${halfMs}ms ease-out both;`,
        `}`,
      ].join('\n'),
    )
  }

  const head = `/* Generated by Keyforge — ${doc.name} (reduced-motion safe) */`
  const body = [
    `@media (prefers-reduced-motion: no-preference) {`,
    indent(fullLayers.join('\n\n')),
    `}`,
    ``,
    `@media (prefers-reduced-motion: reduce) {`,
    indent(reducedLayers.join('\n\n')),
    `}`,
  ].join('\n')

  return `${head}\n\n${body}\n`
}

function indent(css: string): string {
  return css
    .split('\n')
    .map((l) => (l.trim() ? `  ${l}` : l))
    .join('\n')
}
