import type { AnimationDocument } from '@/types'
import { buildKeyframeBlock } from './keyframes'

/**
 * Export production-ready CSS — finite animation shorthand, no preview-only properties.
 */
export function exportCss(doc: AnimationDocument): string {
  const css = doc.layers
    .map((layer) => {
      const animName = `kf-${layer.id}`
      const { times, keyframeBlock } = buildKeyframeBlock(layer, doc.duration)

      if (times.length === 0) return ''

      return [
        `@keyframes ${animName} {`,
        keyframeBlock,
        `}`,
        `[data-layer-id="${layer.id}"] {`,
        `  animation: ${animName} ${doc.duration}ms linear both;`,
        `}`,
      ].join('\n')
    })
    .join('\n\n')

  return `/* Generated by Keyforge — ${doc.name} */\n\n${css}`
}
